### ISSUE TITLE
Empty page for URI

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/www.sailsjs.org#71]
The URI http://sailsjs.org/#/documentation/reference/sails.config/sails.config.policies.html (which was handed out at some point as part of the auto-generated documentation for Sails policies) currently returns a blank page. Not sure what's going on, but I see this in the console.

```
Error: [$location:ihshprfx] http://errors.angularjs.org/1.2.16/$location/ihshprfx?p0=http%3A%2F%2Fsails…cumentation%2Freference%2Fsails.config%2Fsails.config.policies.html&p1=%23!
    at Error (native)
    at http://sailsjs.org/dist/production.e198957d.js:4:29050
    at Object.$$parse (http://sailsjs.org/dist/production.e198957d.js:6:4267)
    at db.$get (http://sailsjs.org/dist/production.e198957d.js:6:5400)
    at Object.d [as invoke] (http://sailsjs.org/dist/production.e198957d.js:5:10983)
    at http://sailsjs.org/dist/production.e198957d.js:5:11743
    at c (http://sailsjs.org/dist/production.e198957d.js:5:10733)
    at Object.d [as invoke] (http://sailsjs.org/dist/production.e198957d.js:5:10948)
    at http://sailsjs.org/dist/production.e198957d.js:5:11743
    at c (http://sailsjs.org/dist/production.e198957d.js:5:10733)(anonymous function) @ production.e198957d.js:6
production.e198957d.js:6 Error: [$location:ihshprfx] http://errors.angularjs.org/1.2.16/$location/ihshprfx?p0=http%3A%2F%2Fsails…cumentation%2Freference%2Fsails.config%2Fsails.config.policies.html&p1=%23!
    at Error (native)
    at http://sailsjs.org/dist/production.e198957d.js:4:29050
    at Object.$$parse (http://sailsjs.org/dist/production.e198957d.js:6:4267)
    at db.$get (http://sailsjs.org/dist/production.e198957d.js:6:5400)
    at Object.d [as invoke] (http://sailsjs.org/dist/production.e198957d.js:5:10983)
    at http://sailsjs.org/dist/production.e198957d.js:5:11743
    at c (http://sailsjs.org/dist/production.e198957d.js:5:10733)
    at d (http://sailsjs.org/dist/production.e198957d.js:5:10948)
    at Object.instantiate (http://sailsjs.org/dist/production.e198957d.js:5:11119)
    at http://sailsjs.org/dist/production.e198957d.js:5:27038
```

**Comment by rachaelshaw** [comment]
Should be redirecting to the right page now
